version: 2
builds:
- id: "beeai"
  dir: beeai
  main: ./cmd
  binary: ./bin/manager
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  ignore:
  - goos: darwin
    goarch: ppc64le
  env:
  - CGO_ENABLED=0
archives:
- ids: [beeai]
kos:           
  - repositories: 
    - kagenti/kagenti-operator/beeai-operator
    working_dir: beeai
    main: ./cmd
    build: beeai
    tags:
    - '{{.Version}}'
    - latest
    bare: true
    preserve_import_paths: false
    platforms:
    - linux/amd64
    - linux/arm64
    env:
    - CGO_ENABLED=0
release:
  draft: false
  prerelease: auto
  mode: keep-existing

