version: 2
builds:
- id: "beeai"
  main: ./beeai/cmd
  binary: bin/beeai
  ldflags:
  - "{{ .Env.LDFLAGS }}"
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  ignore:
  - goos: darwin
    goarch: ppc64le
  env:
  - CGO_ENABLED=0
archives:
- id: beeai
  builds:
  - beeai
kos:           
  - repository: kagenti/kagenti-operator/beeai-operator
    main: ./beeai/cmd
    build: beeai
    tags:
    - '{{.Version}}'
    - latest
    bare: true
    preserve_import_paths: false
    ldflags:
    - "{{ .Env.LDFLAGS }}"
    platforms:
    - linux/amd64
    - linux/arm64
    env:
    - CGO_ENABLED=0
release:
  draft: false
  prerelease: auto
  mode: keep-existing

