apiVersion: aiplatform.aiplatform.io/v1alpha1
kind: ComponentDefinition
metadata:
  labels:
    app.kubernetes.io/name: k8gentai
    app.kubernetes.io/managed-by: kustomize
  name: mcp-tavily-server
spec:
    name: mcp-tavily-server
    namespace: default
    type: app
    installer: deployment
    env:
    - name: TAVILY_API_KEY 
      value: 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       
    defaultParameters:
      image: tavily-mcp-server:latest
