apiVersion: kagenti.operator.dev/v1alpha1
kind: Component
metadata:
  name: my-agent
spec:
  description: My first agent component
  agentComponent:
  
  deployer:
    name: "my-agent-deployment"
    namespace: "default"
    deployAfterBuild: true
    kubernetes:
      imageSpec:
        image: "beai-research-agent"
        imageTag: "latest"
        imageRegistry: "registry.cr-system.svc.cluster.local:5000"
        imagePullPolicy: "IfNotPresent"
    env:
      - name: "LOG_LEVEL"
        value: "INFO"
