apiVersion: kagenti.operator.dev/v1alpha1
kind: Component
metadata:
  name: postgresql
spec:
  description: Postgresql Infra component

  infra:
    infraType: Database
    infraProvider: PostgreSQL

  deployer:
    name: "postgresql"
    namespace: "postgres"
    
    helm:
      chartName: postgresql
      chartRepoName: bitnami
      chartRepoUrl: https://charts.bitnami.com/bitnami
      releaseName: postgresql
      parameters:
        - name: auth.enablePostgresUser
          value: "true"
        - name: auth.postgresPassword
          value: "mysecretpassword"
        - name: primary.livenessProbe.enabled
          value: "false"
        - name: primary.readinessProbe.enabled
          value: "false"

    env:
      - name: "LOG_LEVEL"
        value: "INFO"
