apiVersion: beeai.dev/v1
kind: Component
metadata:
  name: mcp-server-weather
spec:
  # Component type (only one should be specified)
  toolComponent:
    toolType: "MCP"
    build:
      sourceRepository: "github.com/beeai/mcp-server.git"
      sourceRevision: "main"
      repoUser: "beeai-bot"
      sourceCredentials:
        name: "github-token-secret"
      buildOutput:
        image: "mcp-server-weather"
        imageTag: "v1.0.0"
        imageRegistry: "ghcr.io/beeai"
 
  description: "Model Context Provider Server to Fetch Weather Information"
  env:
    - name: HOST
      value: 
    - name: PORT
      value: "10000"
 
  deploymentSpec:
    kubernetesSpec:
      resources:
        limits:
          cpu: "2"
          memory: "4Gi"
        requests:
          cpu: "1"
          memory: "2Gi"
      serviceType: "ClusterIP"
