apiVersion: kagenti.operator.dev/v1alpha1
kind: Component
metadata:
  labels:
    app.kubernetes.io/created-by: streamlit-ui
    app.kubernetes.io/name: kagenti-operator
    kagenti.io/framework: LangGraph
    kagenti.io/protocol: a2a
    kagenti.io/type: agent
  name: weather-service
  namespace: kagenti
spec:
  agent:
    build:
      mode: dev
      pipeline:
        namespace: ""
        parameters:
        - name: SOURCE_REPO_SECRET
          value: github-token-secret
        - name: repo-url
          value: github.com/kagenti/agent-examples
        - name: revision
          value: main
        - name: subfolder-path
          value: a2a/weather_service
        - name: image
          value: registry.cr-system.svc.cluster.local:5000/weather-service:v0.0.1
        steps:
        - configMap: github-clone-step
          enabled: true
          name: github-clone
        - configMap: check-subfolder-step
          enabled: true
          name: folder-verification
        - configMap: kaniko-docker-build-step
          enabled: true
          name: kaniko-build
  deployer:
    deployAfterBuild: true
    env:
    - name: PORT
      value: "8000"
    - name: HOST
      value: 0.0.0.0
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://otel-collector.kagenti-system.svc.cluster.local:8335
    - name: KEYCLOAK_URL
      value: http://keycloak.keycloak.svc.cluster.local:8080
    - name: LLM_API_BASE
      value: http://host.docker.internal:11434/v1
    - name: LLM_API_KEY
      value: dummy
    - name: LLM_MODEL
      value: llama3.2:3b-instruct-fp16
    - name: GITHUB_SECRET_NAME
      value: github-token-secret
    kubernetes:
      containerPorts:
      - containerPort: 8000
        name: http
        protocol: TCP
      imageSpec:
        image: weather-service
        imagePullPolicy: Always
        imageRegistry: registry.cr-system.svc.cluster.local:5000
        imageTag: v0.0.1
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 256Mi
      servicePorts:
      - name: http
        port: 8000
        protocol: TCP
        targetPort: 8000
    name: weather-service
    namespace: kagenti
  description: Agent 'weather-service' built from UI.
  suspend: false
