apiVersion: aiplatform.aiplatform.io/v1alpha1
kind: ComponentDefinition
metadata:
  labels:
    app.kubernetes.io/name: k8gentai
    app.kubernetes.io/managed-by: kustomize
  name: postgresql
spec:
    definitionName: postgresql
    name: postgresql
    namespace: default
    type: infra
    installer: helm
    repoUrl: https://charts.bitnami.com/bitnami
    repoName: bitnami
    chartName: postgresql
    releaseName: postgresql
    defaultParameters:
      auth.enablePostgresUser: "true"
      auth.postgresPassword: mysecretpassword
      primary.livenessProbe.enabled: "false"
      primary.readinessProbe.enabled: "false"  
    dependsOn: []  