apiVersion: aiplatform.aiplatform.io/v1alpha1
kind: ComponentDefinition
metadata:
  labels:
    app.kubernetes.io/name: k8gentai
    app.kubernetes.io/managed-by: kustomize
  name: redis
spec:
    definitionName: redis
    name: redis
    namespace: default
    type: infra
    installer: helm
    repoUrl: https://charts.bitnami.com/bitnami
    repoName: bitnami
    chartName: redis
    releaseName: redis
    defaultParameters:
        master.containerPorts.redis: "6379"
        replica.replicaCount: "1"
        auth.password: "mysecretpassword"
        primary.livenessProbe.enabled: "false"
        primary.readinessProbe.enabled: "false"
    dependsOn: []  