---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kagenti.operator.dev.kagenti.operator.dev
  resources:
  - components
  - platforms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kagenti.operator.dev.kagenti.operator.dev
  resources:
  - components/finalizers
  - platforms/finalizers
  verbs:
  - update
- apiGroups:
  - kagenti.operator.dev.kagenti.operator.dev
  resources:
  - components/status
  - platforms/status
  verbs:
  - get
  - patch
  - update
