apiVersion: beeai.beeai.dev/v1
kind: Agent
metadata:
  name: existing-research-agent
spec:
  description: "Deploying an existing agent image"
  image: "ghcr.io/kagenti/research-agent:v0.0.2"
  env:
    - name: PORT
      value: "8000"
    - name: LLM_MODEL
      value: "llama3.2:3b-instruct-fp16"
    - name: LLM_API_BASE
      value: "http://host.docker.internal:11434/v1"
    - name: LLM_API_KEY
      value: "dummy"  
    - name: PRODUCTION_MODE
      value: "false"
# When using image from a private repo, uncomment below code and create k8s secret
# containing the token      
#    - name: IMAGE_REPO_SECRET
#      value: github-token

  resources:
    limits:
      cpu: "1"
      memory: "2Gi"
    requests:
      cpu: "500m"
      memory: "1Gi"
