name: Build Beeai Operator Docker Image (GHCR)

on:
  push:
    branches:
      - main
    paths:
      - 'beeai/**'
  pull_request:
    branches:
      - main
    paths:
      - 'beeai/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '^1.20'

    - name: Build Beeai Operator
      run: |
        cd beeai
        go build -o beeai-operator ./cmd/main.go

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and Push Docker Image (GHCR)
      uses: docker/build-push-action@v5
      with:
        context: beeai
        push: true
        tags: ghcr.io/kagenti/kagenti-operator/beeai-operator:latest