name: Build Llama Operator Docker Image (GHCR)

permissions:
  contents: write
  packages: write

env:
  REGISTRY: ghcr.io
  REPO: kagenti/kagenti-operator
  CHARTS_PATH: ./charts

on:
  push:
    branches:
      - main
    paths:
      - 'llama/**'
  pull_request:
    branches:
      - main
    paths:
      - 'llama/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '^1.20'

    - name: Build LLama Operator
      run: |
        cd llama
        go build -o llama-operator ./cmd/main.go

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and Push Docker Image (GHCR)
      uses: docker/build-push-action@v5
      with:
        context: llama
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/kagenti/kagenti-operator/llama-operator:latest

    - name: Package and push llama chart
      run: |
        chartVersion=0.0.1
        chartPackageName="kagenti-llama-operator-chart-${chartVersion}.tgz"
        cd ${{ env.CHARTS_PATH }}/llama-operator 
        helm package . --destination . --version ${chartVersion} --app-version ${chartVersion}
        ls -l # List files to check the generated filename
        echo "Chart version: ${chartVersion}" 
        helm push "./${chartPackageName}" oci://${{ env.REGISTRY }}/${{ env.REPO }}